// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAspire.Server.Data;

#nullable disable

namespace TestAspire.Server.Migrations
{
    [DbContext(typeof(InvitationDbContext))]
    [Migration("20260304100000_RemoveEventDateAndPlace")]
    partial class RemoveEventDateAndPlace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TestAspire.Server.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("TestAspire.Server.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Greeting")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("TestAspire.Server.Models.InvitationGuest", b =>
                {
                    b.Property<int>("InvitationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvitationId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("InvitationGuests");
                });

            modelBuilder.Entity("TestAspire.Server.Models.InvitationGuest", b =>
                {
                    b.HasOne("TestAspire.Server.Models.Guest", "Guest")
                        .WithMany("InvitationGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestAspire.Server.Models.Invitation", "Invitation")
                        .WithMany("InvitationGuests")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("TestAspire.Server.Models.Guest", b =>
                {
                    b.Navigation("InvitationGuests");
                });

            modelBuilder.Entity("TestAspire.Server.Models.Invitation", b =>
                {
                    b.Navigation("InvitationGuests");
                });
#pragma warning restore 612, 618
        }
    }
}
